### ISSUE TITLE
Przy tworzeniu transakcji dodać informacje o tym gdzie płacimy / komu przelewamy i dodać nowy typ konta

### ISSUE THREAD

**Issue by Voyda2137** [Voyda2137/banking-app-backend#35]
Dodać typ konta "firmowe"
Przy tworzeniu transakcji getować dane użytkownika, albo firmy do zapisania od kogo przelewane są pieniądze.
Zrobię to za pomocą sprawdzania na jaki typ konta przelewamy, wpłacamy. W przypadku przelewu odbiorcę zawsze wpisywać będzie użytkownik, nadawca będzie brany za pomocą powyższego sposobu.

**Comment by M4xymS** [comment]
Działa poprawnie.
