### ISSUE TITLE
Poprawienie transakcji

### ISSUE THREAD

**Issue by M4xymS** [Voyda2137/banking-app-backend#53]
Podczas gdy transakcje są obecnie operacyjne, istnieje kilka obszarów do optymalizacji.

Dla depozytów / wyplaty: 
- pole receiverInfo można usunąć, ponieważ nadawca pełni rolę zarówno nadawcy, jak i odbiorcy.
-  Dodatkowo można ustanowić domyślny tytuł dla wszystkich depozytów, taki jak "Wpłata gotówki w dniu {moment.format("DD-MM-YYYY")}". 
- Ostatecznie pole destinationAccount jest zbędne, ponieważ pole sourceAccount służy temu samemu celowi.

**Comment by Voyda2137** [comment]
Usunąłem defaultowe wartości w modelu transakcji dla pól date i createdAt. Podczas inicjalizacji programu przypisywany był tam timestamp z chwili zakończenia builda. Aktualnie timestamp jest pobierany w momencie utworzenia transakcji.

**Comment by M4xymS** [comment]
Poprawione, transakcje działają prawidłowo.
